version: "3.9"

services:
  api:
    ports:
      - '8080:8080'
    build:
      context: ./
      dockerfile: ./API/Dockerfile
    networks:
      - backend

  db:
    image: postgres:13-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  postgres_volume: