version: "3.9"

services:
  api:
    ports:
      - '8080:8080'
    build:
      context: ./
      dockerfile: ./API/Dockerfile
    networks:
      - backend

  db:
    image: postgres:13-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    networks:
      - backend
  minio:
    image: minio/minio
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - datastore:/data
    networks:
      - backend
    command: server --console-address ":9001" /data
  createbuckets:
    image: minio/mc
    env_file:
      - .env
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb minio/${MINIO_BUCKET};
      /usr/bin/mc policy set public minio/${MINIO_BUCKET};
      exit 0;
      "

networks:
  backend:
    driver: bridge

volumes:
  postgres_volume:
  datastore: {}